### ISSUE TITLE
brightness bar reset after restarting mac

### ISSUE THREAD

**Issue by unrealwzg** [Bensge/NativeDisplayBrightness#1]
currently, after restarting my mac, brightness bar will be reset to 50%, but the brightness itself will be remembered, if I click F1 the brightness bar show me the 50%.

e.g. before I shutdown my mac I have 30% brightness, and after restart everything looks fine, unless I click F1 or F2 again, the brightness will be set to 50%.and I need to adjust brightness from 50% which is annoying

**Comment by Bensge** [comment]
Thanks for the bug report. The app is meant to save the current brightness when shutting your Mac down, after a restart it will restore the value. It is possible that this mechanism isn't working yet. If the app doesn't find a saved brightness at all, it assumes the brightness is set to 100%.
Keep in mind my app can't keep track of the brightness if you change the monitor brightness with the monitor OSD.

**Comment by unrealwzg** [comment]
The latest release fix my problem, great job Bensge!!! closing this issue.
