### ISSUE TITLE
Hang on shutdown

### ISSUE THREAD

**Issue by superchase9000** [Bensge/NativeDisplayBrightness#2]
NativeDisplayBrightness is causing a hang on shutdown in El Capitan for me. Sierra as well, but hang not as prominent. Quitting the application does not work, but force quitting quitting the application before shutdown alleviates the problem. Console tells me that there is a delay between caught SIGTERM and being forced to quit to reboot. Version .2 did not have these issues.  

<img width="623" alt="screen shot 2017-02-15 at 11 24 41 pm" src="https://cloud.githubusercontent.com/assets/19516003/23008553/f7d174b0-f3d5-11e6-92da-6daff406bff7.png">

**Comment by Bensge** [comment]
Should be fixed in [v0.0.4](https://github.com/Bensge/NativeDisplayBrightness/releases/tag/v0.0.4). Please let me know if it works for you

**Comment by superchase9000** [comment]
Hang seems to be fixed, but the new version, 0.0.4, makes the alert sound like I'm pressing a key that shouldn't be pressed while changing the brightness. Persists through restart.

Not trying to be critical of your work - I love this little app and think it's wonderful! Just trying to submit a bug!

**Comment by Bensge** [comment]
[v0.0.5](https://github.com/Bensge/NativeDisplayBrightness/releases) should fix this issue also

**Comment by superchase9000** [comment]
Works wonderfully! I'm closing this issue. Thanks for your hard work!
